POST http://localhost:3000/cats
accept: application/json
Content-Type: application/json

{ "name": "misifus", "age": 10, "breed": "greek"}
###
GET http://localhost:3000/cats/1
accept: application/json
Content-Type: application/json
