POST http://localhost:3000/user
accept: application/json
Content-Type: application/json

{ "name": "john", "age": 10}
###
GET http://localhost:3000/user
accept: application/json
Content-Type: application/json
