version: "3.5"
services:
  micronaut-dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "5005:5005"
    container_name: "micronaut-dev"
    environment:
      - MICRONAUT_ENVIRONMENTS=dev
      - _JAVA_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - READ_TIMEOUT='20s'
