ehcache:
  caches:
    stores:
      expire-after-write: 15m
    stores-all-name:
      expire-after-write: 15m
    stores-find-by-borough:
      expire-after-write: 15m
    stores-find-by-name:
      expire-after-access: 15m
    stores-find-by-borough-and-name:
      expire-after-access: 15m
    borough-all-names:
      expire-after-access: 15m
